package pokemon.core.domain.model.attribute;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

class AttributeTest {

    @ParameterizedTest(name = "case {index}: {0} is {1} to {2}")
    @MethodSource("provider")
    void getEffectiveness(Attribute attribute, Attribute opponent, Effectiveness expected) {
        var actual = attribute.getEffectiveness(opponent);

        assertThat(actual, is(expected));
    }

    private static Stream<Arguments> provider() {
        return Stream.of(
                Arguments.of(Attribute.NORMAL, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.NORMAL, Attribute.FIRE, Effectiveness.NORMAL),
                Arguments.of(Attribute.NORMAL, Attribute.WATER, Effectiveness.NORMAL),
                Arguments.of(Attribute.NORMAL, Attribute.GRASS, Effectiveness.NORMAL),
                Arguments.of(Attribute.NORMAL, Attribute.ELECTRIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.NORMAL, Attribute.ICE, Effectiveness.NORMAL),
                Arguments.of(Attribute.NORMAL, Attribute.FIGHTING, Effectiveness.NORMAL),
                Arguments.of(Attribute.NORMAL, Attribute.POISON, Effectiveness.NORMAL),
                Arguments.of(Attribute.NORMAL, Attribute.GROUND, Effectiveness.NORMAL),
                Arguments.of(Attribute.NORMAL, Attribute.FLYING, Effectiveness.NORMAL),
                Arguments.of(Attribute.NORMAL, Attribute.PSYCHIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.NORMAL, Attribute.BUG, Effectiveness.NORMAL),
                Arguments.of(Attribute.NORMAL, Attribute.ROCK, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.NORMAL, Attribute.GHOST, Effectiveness.NONE),
                Arguments.of(Attribute.NORMAL, Attribute.DRAGON, Effectiveness.NORMAL),
                Arguments.of(Attribute.NORMAL, Attribute.DARK, Effectiveness.NORMAL),
                Arguments.of(Attribute.NORMAL, Attribute.STEEL, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.NORMAL, Attribute.FAIRY, Effectiveness.NORMAL),

                Arguments.of(Attribute.FIRE, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIRE, Attribute.FIRE, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.FIRE, Attribute.WATER, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.FIRE, Attribute.GRASS, Effectiveness.GOOD),
                Arguments.of(Attribute.FIRE, Attribute.ELECTRIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIRE, Attribute.ICE, Effectiveness.GOOD),
                Arguments.of(Attribute.FIRE, Attribute.FIGHTING, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIRE, Attribute.POISON, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIRE, Attribute.GROUND, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIRE, Attribute.FLYING, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIRE, Attribute.PSYCHIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIRE, Attribute.BUG, Effectiveness.GOOD),
                Arguments.of(Attribute.FIRE, Attribute.ROCK, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.FIRE, Attribute.GHOST, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIRE, Attribute.DRAGON, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.FIRE, Attribute.DARK, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIRE, Attribute.STEEL, Effectiveness.GOOD),
                Arguments.of(Attribute.FIRE, Attribute.FAIRY, Effectiveness.NORMAL),

                Arguments.of(Attribute.WATER, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.WATER, Attribute.FIRE, Effectiveness.GOOD),
                Arguments.of(Attribute.WATER, Attribute.WATER, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.WATER, Attribute.GRASS, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.WATER, Attribute.ELECTRIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.WATER, Attribute.ICE, Effectiveness.NORMAL),
                Arguments.of(Attribute.WATER, Attribute.FIGHTING, Effectiveness.NORMAL),
                Arguments.of(Attribute.WATER, Attribute.POISON, Effectiveness.NORMAL),
                Arguments.of(Attribute.WATER, Attribute.GROUND, Effectiveness.GOOD),
                Arguments.of(Attribute.WATER, Attribute.FLYING, Effectiveness.NORMAL),
                Arguments.of(Attribute.WATER, Attribute.PSYCHIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.WATER, Attribute.BUG, Effectiveness.NORMAL),
                Arguments.of(Attribute.WATER, Attribute.ROCK, Effectiveness.GOOD),
                Arguments.of(Attribute.WATER, Attribute.GHOST, Effectiveness.NORMAL),
                Arguments.of(Attribute.WATER, Attribute.DRAGON, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.WATER, Attribute.DARK, Effectiveness.NORMAL),
                Arguments.of(Attribute.WATER, Attribute.STEEL, Effectiveness.NORMAL),
                Arguments.of(Attribute.WATER, Attribute.FAIRY, Effectiveness.NORMAL),

                Arguments.of(Attribute.GRASS, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.GRASS, Attribute.FIRE, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.GRASS, Attribute.WATER, Effectiveness.GOOD),
                Arguments.of(Attribute.GRASS, Attribute.GRASS, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.GRASS, Attribute.ELECTRIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.GRASS, Attribute.ICE, Effectiveness.NORMAL),
                Arguments.of(Attribute.GRASS, Attribute.FIGHTING, Effectiveness.NORMAL),
                Arguments.of(Attribute.GRASS, Attribute.POISON, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.GRASS, Attribute.GROUND, Effectiveness.GOOD),
                Arguments.of(Attribute.GRASS, Attribute.FLYING, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.GRASS, Attribute.PSYCHIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.GRASS, Attribute.BUG, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.GRASS, Attribute.ROCK, Effectiveness.GOOD),
                Arguments.of(Attribute.GRASS, Attribute.GHOST, Effectiveness.NORMAL),
                Arguments.of(Attribute.GRASS, Attribute.DRAGON, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.GRASS, Attribute.DARK, Effectiveness.NORMAL),
                Arguments.of(Attribute.GRASS, Attribute.STEEL, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.GRASS, Attribute.FAIRY, Effectiveness.NORMAL),

                Arguments.of(Attribute.ELECTRIC, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.ELECTRIC, Attribute.FIRE, Effectiveness.NORMAL),
                Arguments.of(Attribute.ELECTRIC, Attribute.WATER, Effectiveness.GOOD),
                Arguments.of(Attribute.ELECTRIC, Attribute.GRASS, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.ELECTRIC, Attribute.ELECTRIC, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.ELECTRIC, Attribute.ICE, Effectiveness.NORMAL),
                Arguments.of(Attribute.ELECTRIC, Attribute.FIGHTING, Effectiveness.NORMAL),
                Arguments.of(Attribute.ELECTRIC, Attribute.POISON, Effectiveness.NORMAL),
                Arguments.of(Attribute.ELECTRIC, Attribute.GROUND, Effectiveness.NONE),
                Arguments.of(Attribute.ELECTRIC, Attribute.FLYING, Effectiveness.GOOD),
                Arguments.of(Attribute.ELECTRIC, Attribute.PSYCHIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.ELECTRIC, Attribute.BUG, Effectiveness.NORMAL),
                Arguments.of(Attribute.ELECTRIC, Attribute.ROCK, Effectiveness.NORMAL),
                Arguments.of(Attribute.ELECTRIC, Attribute.GHOST, Effectiveness.NORMAL),
                Arguments.of(Attribute.ELECTRIC, Attribute.DRAGON, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.ELECTRIC, Attribute.DARK, Effectiveness.NORMAL),
                Arguments.of(Attribute.ELECTRIC, Attribute.STEEL, Effectiveness.NORMAL),
                Arguments.of(Attribute.ELECTRIC, Attribute.FAIRY, Effectiveness.NORMAL),

                Arguments.of(Attribute.ICE, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.ICE, Attribute.FIRE, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.ICE, Attribute.WATER, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.ICE, Attribute.GRASS, Effectiveness.GOOD),
                Arguments.of(Attribute.ICE, Attribute.ELECTRIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.ICE, Attribute.ICE, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.ICE, Attribute.FIGHTING, Effectiveness.NORMAL),
                Arguments.of(Attribute.ICE, Attribute.POISON, Effectiveness.NORMAL),
                Arguments.of(Attribute.ICE, Attribute.GROUND, Effectiveness.GOOD),
                Arguments.of(Attribute.ICE, Attribute.FLYING, Effectiveness.GOOD),
                Arguments.of(Attribute.ICE, Attribute.PSYCHIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.ICE, Attribute.BUG, Effectiveness.NORMAL),
                Arguments.of(Attribute.ICE, Attribute.ROCK, Effectiveness.NORMAL),
                Arguments.of(Attribute.ICE, Attribute.GHOST, Effectiveness.NORMAL),
                Arguments.of(Attribute.ICE, Attribute.DRAGON, Effectiveness.GOOD),
                Arguments.of(Attribute.ICE, Attribute.DARK, Effectiveness.NORMAL),
                Arguments.of(Attribute.ICE, Attribute.STEEL, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.ICE, Attribute.FAIRY, Effectiveness.NORMAL),

                Arguments.of(Attribute.FIGHTING, Attribute.NORMAL, Effectiveness.GOOD),
                Arguments.of(Attribute.FIGHTING, Attribute.FIRE, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIGHTING, Attribute.WATER, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIGHTING, Attribute.GRASS, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIGHTING, Attribute.ELECTRIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIGHTING, Attribute.ICE, Effectiveness.GOOD),
                Arguments.of(Attribute.FIGHTING, Attribute.FIGHTING, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIGHTING, Attribute.POISON, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.FIGHTING, Attribute.GROUND, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIGHTING, Attribute.FLYING, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.FIGHTING, Attribute.PSYCHIC, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.FIGHTING, Attribute.BUG, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.FIGHTING, Attribute.ROCK, Effectiveness.GOOD),
                Arguments.of(Attribute.FIGHTING, Attribute.GHOST, Effectiveness.NONE),
                Arguments.of(Attribute.FIGHTING, Attribute.DRAGON, Effectiveness.NORMAL),
                Arguments.of(Attribute.FIGHTING, Attribute.DARK, Effectiveness.GOOD),
                Arguments.of(Attribute.FIGHTING, Attribute.STEEL, Effectiveness.GOOD),
                Arguments.of(Attribute.FIGHTING, Attribute.FAIRY, Effectiveness.NOT_GOOD),

                Arguments.of(Attribute.POISON, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.POISON, Attribute.FIRE, Effectiveness.NORMAL),
                Arguments.of(Attribute.POISON, Attribute.WATER, Effectiveness.NORMAL),
                Arguments.of(Attribute.POISON, Attribute.GRASS, Effectiveness.GOOD),
                Arguments.of(Attribute.POISON, Attribute.ELECTRIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.POISON, Attribute.ICE, Effectiveness.NORMAL),
                Arguments.of(Attribute.POISON, Attribute.FIGHTING, Effectiveness.NORMAL),
                Arguments.of(Attribute.POISON, Attribute.POISON, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.POISON, Attribute.GROUND, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.POISON, Attribute.FLYING, Effectiveness.NORMAL),
                Arguments.of(Attribute.POISON, Attribute.PSYCHIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.POISON, Attribute.BUG, Effectiveness.NORMAL),
                Arguments.of(Attribute.POISON, Attribute.ROCK, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.POISON, Attribute.GHOST, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.POISON, Attribute.DRAGON, Effectiveness.NORMAL),
                Arguments.of(Attribute.POISON, Attribute.DARK, Effectiveness.NORMAL),
                Arguments.of(Attribute.POISON, Attribute.STEEL, Effectiveness.NONE),
                Arguments.of(Attribute.POISON, Attribute.FAIRY, Effectiveness.GOOD),

                Arguments.of(Attribute.GROUND, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.GROUND, Attribute.FIRE, Effectiveness.GOOD),
                Arguments.of(Attribute.GROUND, Attribute.WATER, Effectiveness.NORMAL),
                Arguments.of(Attribute.GROUND, Attribute.GRASS, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.GROUND, Attribute.ELECTRIC, Effectiveness.GOOD),
                Arguments.of(Attribute.GROUND, Attribute.ICE, Effectiveness.NORMAL),
                Arguments.of(Attribute.GROUND, Attribute.FIGHTING, Effectiveness.NORMAL),
                Arguments.of(Attribute.GROUND, Attribute.POISON, Effectiveness.GOOD),
                Arguments.of(Attribute.GROUND, Attribute.GROUND, Effectiveness.NORMAL),
                Arguments.of(Attribute.GROUND, Attribute.FLYING, Effectiveness.NONE),
                Arguments.of(Attribute.GROUND, Attribute.PSYCHIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.GROUND, Attribute.BUG, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.GROUND, Attribute.ROCK, Effectiveness.GOOD),
                Arguments.of(Attribute.GROUND, Attribute.GHOST, Effectiveness.NORMAL),
                Arguments.of(Attribute.GROUND, Attribute.DRAGON, Effectiveness.NORMAL),
                Arguments.of(Attribute.GROUND, Attribute.DARK, Effectiveness.NORMAL),
                Arguments.of(Attribute.GROUND, Attribute.STEEL, Effectiveness.GOOD),
                Arguments.of(Attribute.GROUND, Attribute.FAIRY, Effectiveness.NORMAL),

                Arguments.of(Attribute.FLYING, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.FLYING, Attribute.FIRE, Effectiveness.NORMAL),
                Arguments.of(Attribute.FLYING, Attribute.WATER, Effectiveness.NORMAL),
                Arguments.of(Attribute.FLYING, Attribute.GRASS, Effectiveness.GOOD),
                Arguments.of(Attribute.FLYING, Attribute.ELECTRIC, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.FLYING, Attribute.ICE, Effectiveness.NORMAL),
                Arguments.of(Attribute.FLYING, Attribute.FIGHTING, Effectiveness.GOOD),
                Arguments.of(Attribute.FLYING, Attribute.POISON, Effectiveness.NORMAL),
                Arguments.of(Attribute.FLYING, Attribute.GROUND, Effectiveness.NORMAL),
                Arguments.of(Attribute.FLYING, Attribute.FLYING, Effectiveness.NORMAL),
                Arguments.of(Attribute.FLYING, Attribute.PSYCHIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.FLYING, Attribute.BUG, Effectiveness.GOOD),
                Arguments.of(Attribute.FLYING, Attribute.ROCK, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.FLYING, Attribute.GHOST, Effectiveness.NORMAL),
                Arguments.of(Attribute.FLYING, Attribute.DRAGON, Effectiveness.NORMAL),
                Arguments.of(Attribute.FLYING, Attribute.DARK, Effectiveness.NORMAL),
                Arguments.of(Attribute.FLYING, Attribute.STEEL, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.FLYING, Attribute.FAIRY, Effectiveness.NORMAL),

                Arguments.of(Attribute.PSYCHIC, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.PSYCHIC, Attribute.FIRE, Effectiveness.NORMAL),
                Arguments.of(Attribute.PSYCHIC, Attribute.WATER, Effectiveness.NORMAL),
                Arguments.of(Attribute.PSYCHIC, Attribute.GRASS, Effectiveness.NORMAL),
                Arguments.of(Attribute.PSYCHIC, Attribute.ELECTRIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.PSYCHIC, Attribute.ICE, Effectiveness.NORMAL),
                Arguments.of(Attribute.PSYCHIC, Attribute.FIGHTING, Effectiveness.GOOD),
                Arguments.of(Attribute.PSYCHIC, Attribute.POISON, Effectiveness.GOOD),
                Arguments.of(Attribute.PSYCHIC, Attribute.GROUND, Effectiveness.NORMAL),
                Arguments.of(Attribute.PSYCHIC, Attribute.FLYING, Effectiveness.NORMAL),
                Arguments.of(Attribute.PSYCHIC, Attribute.PSYCHIC, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.PSYCHIC, Attribute.BUG, Effectiveness.NORMAL),
                Arguments.of(Attribute.PSYCHIC, Attribute.ROCK, Effectiveness.NORMAL),
                Arguments.of(Attribute.PSYCHIC, Attribute.GHOST, Effectiveness.NORMAL),
                Arguments.of(Attribute.PSYCHIC, Attribute.DRAGON, Effectiveness.NORMAL),
                Arguments.of(Attribute.PSYCHIC, Attribute.DARK, Effectiveness.NONE),
                Arguments.of(Attribute.PSYCHIC, Attribute.STEEL, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.PSYCHIC, Attribute.FAIRY, Effectiveness.NORMAL),

                Arguments.of(Attribute.BUG, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.BUG, Attribute.FIRE, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.BUG, Attribute.WATER, Effectiveness.NORMAL),
                Arguments.of(Attribute.BUG, Attribute.GRASS, Effectiveness.GOOD),
                Arguments.of(Attribute.BUG, Attribute.ELECTRIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.BUG, Attribute.ICE, Effectiveness.NORMAL),
                Arguments.of(Attribute.BUG, Attribute.FIGHTING, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.BUG, Attribute.POISON, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.BUG, Attribute.GROUND, Effectiveness.NORMAL),
                Arguments.of(Attribute.BUG, Attribute.FLYING, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.BUG, Attribute.PSYCHIC, Effectiveness.GOOD),
                Arguments.of(Attribute.BUG, Attribute.BUG, Effectiveness.NORMAL),
                Arguments.of(Attribute.BUG, Attribute.ROCK, Effectiveness.NORMAL),
                Arguments.of(Attribute.BUG, Attribute.GHOST, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.BUG, Attribute.DRAGON, Effectiveness.NORMAL),
                Arguments.of(Attribute.BUG, Attribute.DARK, Effectiveness.GOOD),
                Arguments.of(Attribute.BUG, Attribute.STEEL, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.BUG, Attribute.FAIRY, Effectiveness.NOT_GOOD),

                Arguments.of(Attribute.ROCK, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.ROCK, Attribute.FIRE, Effectiveness.GOOD),
                Arguments.of(Attribute.ROCK, Attribute.WATER, Effectiveness.NORMAL),
                Arguments.of(Attribute.ROCK, Attribute.GRASS, Effectiveness.NORMAL),
                Arguments.of(Attribute.ROCK, Attribute.ELECTRIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.ROCK, Attribute.ICE, Effectiveness.GOOD),
                Arguments.of(Attribute.ROCK, Attribute.FIGHTING, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.ROCK, Attribute.POISON, Effectiveness.NORMAL),
                Arguments.of(Attribute.ROCK, Attribute.GROUND, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.ROCK, Attribute.FLYING, Effectiveness.GOOD),
                Arguments.of(Attribute.ROCK, Attribute.PSYCHIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.ROCK, Attribute.BUG, Effectiveness.GOOD),
                Arguments.of(Attribute.ROCK, Attribute.ROCK, Effectiveness.NORMAL),
                Arguments.of(Attribute.ROCK, Attribute.GHOST, Effectiveness.NORMAL),
                Arguments.of(Attribute.ROCK, Attribute.DRAGON, Effectiveness.NORMAL),
                Arguments.of(Attribute.ROCK, Attribute.DARK, Effectiveness.NORMAL),
                Arguments.of(Attribute.ROCK, Attribute.STEEL, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.ROCK, Attribute.FAIRY, Effectiveness.NORMAL),

                Arguments.of(Attribute.GHOST, Attribute.NORMAL, Effectiveness.NONE),
                Arguments.of(Attribute.GHOST, Attribute.FIRE, Effectiveness.NORMAL),
                Arguments.of(Attribute.GHOST, Attribute.WATER, Effectiveness.NORMAL),
                Arguments.of(Attribute.GHOST, Attribute.GRASS, Effectiveness.NORMAL),
                Arguments.of(Attribute.GHOST, Attribute.ELECTRIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.GHOST, Attribute.ICE, Effectiveness.NORMAL),
                Arguments.of(Attribute.GHOST, Attribute.FIGHTING, Effectiveness.NORMAL),
                Arguments.of(Attribute.GHOST, Attribute.POISON, Effectiveness.NORMAL),
                Arguments.of(Attribute.GHOST, Attribute.GROUND, Effectiveness.NORMAL),
                Arguments.of(Attribute.GHOST, Attribute.FLYING, Effectiveness.NORMAL),
                Arguments.of(Attribute.GHOST, Attribute.PSYCHIC, Effectiveness.GOOD),
                Arguments.of(Attribute.GHOST, Attribute.BUG, Effectiveness.NORMAL),
                Arguments.of(Attribute.GHOST, Attribute.ROCK, Effectiveness.NORMAL),
                Arguments.of(Attribute.GHOST, Attribute.GHOST, Effectiveness.GOOD),
                Arguments.of(Attribute.GHOST, Attribute.DRAGON, Effectiveness.NORMAL),
                Arguments.of(Attribute.GHOST, Attribute.DARK, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.GHOST, Attribute.STEEL, Effectiveness.NORMAL),
                Arguments.of(Attribute.GHOST, Attribute.FAIRY, Effectiveness.NORMAL),

                Arguments.of(Attribute.DRAGON, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.DRAGON, Attribute.FIRE, Effectiveness.NORMAL),
                Arguments.of(Attribute.DRAGON, Attribute.WATER, Effectiveness.NORMAL),
                Arguments.of(Attribute.DRAGON, Attribute.GRASS, Effectiveness.NORMAL),
                Arguments.of(Attribute.DRAGON, Attribute.ELECTRIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.DRAGON, Attribute.ICE, Effectiveness.NORMAL),
                Arguments.of(Attribute.DRAGON, Attribute.FIGHTING, Effectiveness.NORMAL),
                Arguments.of(Attribute.DRAGON, Attribute.POISON, Effectiveness.NORMAL),
                Arguments.of(Attribute.DRAGON, Attribute.GROUND, Effectiveness.NORMAL),
                Arguments.of(Attribute.DRAGON, Attribute.FLYING, Effectiveness.NORMAL),
                Arguments.of(Attribute.DRAGON, Attribute.PSYCHIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.DRAGON, Attribute.BUG, Effectiveness.NORMAL),
                Arguments.of(Attribute.DRAGON, Attribute.ROCK, Effectiveness.NORMAL),
                Arguments.of(Attribute.DRAGON, Attribute.GHOST, Effectiveness.NORMAL),
                Arguments.of(Attribute.DRAGON, Attribute.DRAGON, Effectiveness.GOOD),
                Arguments.of(Attribute.DRAGON, Attribute.DARK, Effectiveness.NORMAL),
                Arguments.of(Attribute.DRAGON, Attribute.STEEL, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.DRAGON, Attribute.FAIRY, Effectiveness.NONE),

                Arguments.of(Attribute.DARK, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.DARK, Attribute.FIRE, Effectiveness.NORMAL),
                Arguments.of(Attribute.DARK, Attribute.WATER, Effectiveness.NORMAL),
                Arguments.of(Attribute.DARK, Attribute.GRASS, Effectiveness.NORMAL),
                Arguments.of(Attribute.DARK, Attribute.ELECTRIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.DARK, Attribute.ICE, Effectiveness.NORMAL),
                Arguments.of(Attribute.DARK, Attribute.FIGHTING, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.DARK, Attribute.POISON, Effectiveness.NORMAL),
                Arguments.of(Attribute.DARK, Attribute.GROUND, Effectiveness.NORMAL),
                Arguments.of(Attribute.DARK, Attribute.FLYING, Effectiveness.NORMAL),
                Arguments.of(Attribute.DARK, Attribute.PSYCHIC, Effectiveness.GOOD),
                Arguments.of(Attribute.DARK, Attribute.BUG, Effectiveness.NORMAL),
                Arguments.of(Attribute.DARK, Attribute.ROCK, Effectiveness.NORMAL),
                Arguments.of(Attribute.DARK, Attribute.GHOST, Effectiveness.GOOD),
                Arguments.of(Attribute.DARK, Attribute.DRAGON, Effectiveness.NORMAL),
                Arguments.of(Attribute.DARK, Attribute.DARK, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.DARK, Attribute.STEEL, Effectiveness.NORMAL),
                Arguments.of(Attribute.DARK, Attribute.FAIRY, Effectiveness.NOT_GOOD),

                Arguments.of(Attribute.STEEL, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.STEEL, Attribute.FIRE, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.STEEL, Attribute.WATER, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.STEEL, Attribute.GRASS, Effectiveness.NORMAL),
                Arguments.of(Attribute.STEEL, Attribute.ELECTRIC, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.STEEL, Attribute.ICE, Effectiveness.GOOD),
                Arguments.of(Attribute.STEEL, Attribute.FIGHTING, Effectiveness.NORMAL),
                Arguments.of(Attribute.STEEL, Attribute.POISON, Effectiveness.NORMAL),
                Arguments.of(Attribute.STEEL, Attribute.GROUND, Effectiveness.NORMAL),
                Arguments.of(Attribute.STEEL, Attribute.FLYING, Effectiveness.NORMAL),
                Arguments.of(Attribute.STEEL, Attribute.PSYCHIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.STEEL, Attribute.BUG, Effectiveness.NORMAL),
                Arguments.of(Attribute.STEEL, Attribute.ROCK, Effectiveness.GOOD),
                Arguments.of(Attribute.STEEL, Attribute.GHOST, Effectiveness.NORMAL),
                Arguments.of(Attribute.STEEL, Attribute.DRAGON, Effectiveness.NORMAL),
                Arguments.of(Attribute.STEEL, Attribute.DARK, Effectiveness.NORMAL),
                Arguments.of(Attribute.STEEL, Attribute.STEEL, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.STEEL, Attribute.FAIRY, Effectiveness.GOOD),

                Arguments.of(Attribute.FAIRY, Attribute.NORMAL, Effectiveness.NORMAL),
                Arguments.of(Attribute.FAIRY, Attribute.FIRE, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.FAIRY, Attribute.WATER, Effectiveness.NORMAL),
                Arguments.of(Attribute.FAIRY, Attribute.GRASS, Effectiveness.NORMAL),
                Arguments.of(Attribute.FAIRY, Attribute.ELECTRIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.FAIRY, Attribute.ICE, Effectiveness.NORMAL),
                Arguments.of(Attribute.FAIRY, Attribute.FIGHTING, Effectiveness.GOOD),
                Arguments.of(Attribute.FAIRY, Attribute.POISON, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.FAIRY, Attribute.GROUND, Effectiveness.NORMAL),
                Arguments.of(Attribute.FAIRY, Attribute.FLYING, Effectiveness.NORMAL),
                Arguments.of(Attribute.FAIRY, Attribute.PSYCHIC, Effectiveness.NORMAL),
                Arguments.of(Attribute.FAIRY, Attribute.BUG, Effectiveness.NORMAL),
                Arguments.of(Attribute.FAIRY, Attribute.ROCK, Effectiveness.NORMAL),
                Arguments.of(Attribute.FAIRY, Attribute.GHOST, Effectiveness.NORMAL),
                Arguments.of(Attribute.FAIRY, Attribute.DRAGON, Effectiveness.GOOD),
                Arguments.of(Attribute.FAIRY, Attribute.DARK, Effectiveness.GOOD),
                Arguments.of(Attribute.FAIRY, Attribute.STEEL, Effectiveness.NOT_GOOD),
                Arguments.of(Attribute.FAIRY, Attribute.FAIRY, Effectiveness.NORMAL)
        );
    }
}